name: dartbug
publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  collection: ^1.17.2
  gcp: ^0.1.0
  http: ^0.13.4
  shelf: ^1.0.0

dev_dependencies:
  dart_flutter_team_lints: ^1.0.0
  github: ^9.16.0
  test: ^1.24.3
